### ISSUE TITLE
K=25

### ISSUE THREAD

**Issue by stepsolar** [alexdelprete/ha-sinapsi-alfa#19]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, I have another alpha installed on a three-phase meter with 80kw power. From alpha they had to modify the reading values ​​per app by multiplying by 25 so as to have the real values, but I notice that these multiplied values ​​on the alpha app are not read on your integration which still reads the non-multiplied values. Would it be possible to multiply by 25? It would be nice to include in the configuration both the alpha IP and another field whether or not to multiply by 25 which would be the K coefficient. K=25 is also talked about on the internet. Thank you

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by alexdelprete** [comment]
Ask Sinapsi to publish these values in modbus. Probaly the register map changed and they added these specific values in other addresses. I have to stick to the default register map.

Meanwhile, if it’s just a *25 problem, you can create template sensors and multiply the alpha sensors by 25.

**Comment by stepsolar** [comment]
Thanks, I will ask sinaspi if this modification is possible.  I had also thought about creating other sensors *25 but I don't like it.  Thank you

**Comment by alexdelprete** [comment]
What is this K coefficient? I can't find much about K=25, you said there is docs on the internet.

**Comment by alexdelprete** [comment]
Ok, found it. Sinapsi has to publish the K coefficient in modbus, so I will always multiply it, default should be 1, so it's ok, if in your case it's 25 it will show the correct values.

![](https://i.imgur.com/8FjJ2nM.png)

**Comment by stepsolar** [comment]
On their app they have already changed the value but on the modbus I still receive the non-multiplied values

**Comment by alexdelprete** [comment]
> On their app they have already changed the value but on the modbus I still receive the non-multiplied values

Ask them if the Power Factor is available in the modbus registers. If not, ask them to implement it. ;)

I asked them to implement the serial number of the device in modbus, but they didn't do it.

**Comment by stepsolar** [comment]
I have already sent an email, I hope now that they will also modify the K coefficient in Modbus, otherwise I will create the sensors by multiplying them by 25. Couldn't you create the possibility of multiplying by 25 in your app?  So do you automatically create the correct sensors?

**Comment by alexdelprete** [comment]
You don't like template sensors, and I don't like managing the K factor manually in the integration, it should be provided by the meter, as Shelly EM or other meters do.

In case Sinapsi won't implement it, I'll think about it...but I don't like it.

**Comment by alexdelprete** [comment]
> Thanks, if you increase it I think it will be useful for me but also for others, otherwise you always have to ask sinaspi since it is an unmanageable setting.

you forget 1 thing: in your case K=25 but in other cases it might be a different value that is also dynamic, not static, so it can change. Having it configured as a static value is a wrong approach.

K must be provided by the meter.

**Comment by alexdelprete** [comment]
Te lo spiego in italiano: nel tuo caso il K=25, ma in altri casi il K potrebbe variare dinamicamente. è errato metterlo come valore statico.

mi spiace ma non lo farò. creati dei template sensor per ora, e cerca di spiegare a Sinapsi che il K deve essere disponibile nella mappa modbus.

**Comment by stepsolar** [comment]
Mi hanno risposto, non riescono a moltiplicare i codici modbus x25. La soluzione è creare dei nuovi sensori moltiplicati. Che brutta cosa..

**Comment by alexdelprete** [comment]
Non riescono? 😂

Non vogliono, è diverso.

**Comment by stepsolar** [comment]
Ho notato che alcuni valori sono corretti come ad esempio potenza prodotta, la potenza immersa deve essere moltiplicata e automaticamente il valore potenza auto consumata è sbagliata perché viene soltratto con un valore errato..

**Comment by alexdelprete** [comment]
Fammi vedere schermata con i sensori, qui i calcoli sembrano corretti. Mostrami schermata con tutti i sensori e descrivimi perché non ti tornano i calcoli.

**Comment by alexdelprete** [comment]
Apri un altro issue con le info che ti ho richiesto, questo è chiuso.

**Comment by stepsolar** [comment]
Allego foto con le differenze... 
![Screenshot_2024-05-01-15-34-32-763_com sinapsi alfa](https://github.com/alexdelprete/ha-sinapsi-alfa/assets/84263865/5d24f9c3-968d-4fbe-a5f7-39f33cbf0f22)
![Screenshot_2024-05-01-15-34-37-593_io homeassistant companion android](https://github.com/alexdelprete/ha-sinapsi-alfa/assets/84263865/7b0bd280-dec6-45fb-a8eb-85abee5871bc)

**Comment by alexdelprete** [comment]
L'unico valore calcolato è l'autoconsumo, il resto me lo restituisce Alfa dai registri modbus.

Quale valore non ti torna, l'autoconsumo?

**Comment by stepsolar** [comment]
Si,
Autoconsumo non torna.



Il gio 2 mag 2024, 00:05 Alessandro Del Prete ***@***.***> ha
scritto:

**Comment by alexdelprete** [comment]
Dai tuoi screenshot non si vede Energia immessa totale.

Il calcolo è semplice: `energia/potenza autoconsumata = energia/potenza prodotta - energia/potenza immessa`

Questo è il codice:

```python
    if reg_type == "calcolato":
        self.data["potenza_auto_consumata"] = (
            self.data["potenza_prodotta"] - self.data["potenza_immessa"]
        )
        self.data["potenza_consumata"] = (
            self.data["potenza_auto_consumata"]
            + self.data["potenza_prelevata"]
        )

        self.data["energia_auto_consumata"] = (
            self.data["energia_prodotta"] - self.data["energia_immessa"]
        )
        self.data["energia_consumata"] = (
            self.data["energia_auto_consumata"]
            + self.data["energia_prelevata"]
        )
```

**Comment by stepsolar** [comment]
Dovrei sostituire i tuoi sensori con i miei che ho dovuto moltiplicare x 25.
Altrimenti se ci fosse la possibilità al tuo codice inserirei la moltiplicazione così poi le vari sostrazzioni saranno con i valori corretti. Dove potrei inserire la moltiplicazione?

**Comment by alexdelprete** [comment]
Ma che ci vuole a creare dei template sensor dove ti fai la moltiplicazione. Non capisco cos'è che ti dia fastidio...:)

**Comment by stepsolar** [comment]
Si li ho ho creati ma non mi piace, quando apro la tua integrazione vedo tutti i dati sbagliati e questo non lo sopporto. Ho atteso tanto per questa integrazione e adesso..

**Comment by alexdelprete** [comment]
Devi prendertela con Sinapsi. Non ci vuole molto a pubblicare il K nei registri modbus. Se lo fanno, implementerò la modifica.

**Comment by stepsolar** [comment]
Mi hanno risposto "noi a monte non fissiamo fare niente, deve configurare homeassistant in modo che i valori vengono moltiplicati per 25"
Che tristezza... Ti devi immaginare che ho notato di nuovo valori non corretti sulla loro app come se il parametro 25 sia stato tolto, e ho fatto nuovamente segnalazione.. Spero che non danno adesso la colpa al distributore "E-distribuzione"...

**Comment by alexdelprete** [comment]
Digli così: "il fattore K viene fornito dal contatore e-distribuzione, quindi Alfa dovrebbe leggerlo e calcolare i valori REALI e fornire valori REALI nell'app e via modbus. Dovrebbe anche fornire via modbus il fattore K letto dal contatore."

**Comment by stepsolar** [comment]
Ecco qui la risposta che mi hanno dato: "Buongiorno,
non è così perché i valori forniti dal contatore sono privi della costante di trasformazione K, per questo motivo devono essere sempre moltiplicati per quel valore."

**Comment by alexdelprete** [comment]
Dalla documentazione del contatore openmeter si evince che il valore viene mostrato dal contatore:

![image](https://github.com/alexdelprete/ha-sinapsi-alfa/assets/7027842/485772de-e2ee-4e88-aea7-0e5b14c23408)

**Comment by stepsolar** [comment]
Sono andato nel contatore, cliccando sul display non ho trovato nulla sul valore K o valore 25.

**Comment by alexdelprete** [comment]
> Sono andato nel contatore, cliccando sul display non ho trovato nulla sul valore K o valore 25.

La documentazione dice che lo trovi nel menu "Lista spiegazione simboli". Ma io non ho quel contatore, chiedi ad e-distribuzione come visualizzarlo.
